### ISSUE TITLE
Proposal. Structure MSA.BuildingBlocks readme

### ISSUE THREAD

**Issue by kanilsz** [Marusyk/MSA.BuildingBlocks#4]
Would be great to have read me on every package with examples of use.
Also update MSA.BuildingBlocks read me with urls on this readmes.

**Comment by Marusyk** [comment]
+++
If you are interested in, go ahead.
It can also be used for your feature projects

**Comment by kanilsz** [comment]
> +++ If you are interested in, go ahead. It can also be used for your feature projects

Of course, so I proposed because could try and so it. I will do it in near future ( for now don't have opportunity to do so estimete)

**Comment by kanilsz** [comment]
It could be linked to branch https://github.com/Marusyk/MSA.BuildingBlocks/pull/6
