### ISSUE TITLE
Releasing MSA.BuildingBlocks.ServiceClient version 1.0.0

### ISSUE THREAD

**Issue by kanilsz** [Marusyk/MSA.BuildingBlocks#7]
Hi. I want to use a new version of the ServiceClient package. Could you please release it?

**Comment by kanilsz** [comment]
Also, it is not for this case. But I found an issue with an example.  I could fix it. Could I create the issue for that case and commit under that number?

**Comment by Marusyk** [comment]
Are you going to prepare the fix before release?

**Comment by kanilsz** [comment]
Yes, sry, going to make it today.
